"""crea catalogo productos

Revision ID: 1a81a5e6e75b
Revises:
Create Date: 2026-09-07 17:33:01.015620

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1a81a5e6e75b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "productos",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.String(length=20), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("categoria", sa.String(length=20), nullable=False),
        sa.Column("stock_inicial", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "estado", sa.String(length=10), server_default="activo", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "categoria IN ('videojuego','consola','accesorio')",
            name="ck_productos_categoria",
        ),
        sa.CheckConstraint(
            "estado IN ('activo','inactivo')", name="ck_productos_estado"
        ),
        # Postgres: sku ~ '^[A-Z0-9_-]{3,20}$' — adaptado a SQLite para verificación local
        sa.CheckConstraint(
            "length(sku) BETWEEN 3 AND 20", name="ck_productos_sku_regex"
        ),
        sa.CheckConstraint(
            "length(trim(nombre)) BETWEEN 2 AND 100", name="ck_productos_nombre_length"
        ),
        sa.CheckConstraint(
            "stock_inicial >= 0 AND stock_inicial <= 1000000",
            name="ck_productos_stock_inicial",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_productos_categoria", "productos", ["categoria"], unique=False)
    op.create_index(op.f("ix_productos_estado"), "productos", ["estado"], unique=False)
    op.create_index("ix_productos_sku", "productos", ["sku"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_productos_sku", table_name="productos")
    op.drop_index(op.f("ix_productos_estado"), table_name="productos")
    op.drop_index("ix_productos_categoria", table_name="productos")
    op.drop_table("productos")
    # ### end Alembic commands ###
