"""crea ventas 012

Revision ID: 2c3245f4f658
Revises: ff5b41c7a385
Create Date: 2026-09-20 16:52:28.361684

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c3245f4f658"
down_revision: Union[str, Sequence[str], None] = "ff5b41c7a385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ventas",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("cliente_nombre", sa.String(length=100), nullable=False),
        sa.Column("cliente_email", sa.String(length=254), nullable=True),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint(
            "length(trim(cliente_nombre)) BETWEEN 2 AND 100",
            name="ck_ventas_cliente_nombre",
        ),
        sa.CheckConstraint("total >= 0", name="ck_ventas_total"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ventas_created_at", "ventas", ["created_at"], unique=False)
    op.create_table(
        "venta_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("venta_id", sa.Integer(), nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("movimiento_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "cantidad > 0 AND cantidad <= 1000000", name="ck_venta_items_cantidad"
        ),
        sa.CheckConstraint(
            "precio_unitario >= 0 AND precio_unitario <= 1000000",
            name="ck_venta_items_precio",
        ),
        sa.ForeignKeyConstraint(
            ["movimiento_id"], ["movimientos_inventario.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["producto_id"], ["productos.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["venta_id"], ["ventas.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("movimiento_id"),
    )
    op.create_index(
        "ix_venta_items_movimiento_id", "venta_items", ["movimiento_id"], unique=True
    )
    op.create_index(
        op.f("ix_venta_items_producto_id"), "venta_items", ["producto_id"], unique=False
    )
    op.create_index(
        op.f("ix_venta_items_venta_id"), "venta_items", ["venta_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_venta_items_venta_id"), table_name="venta_items")
    op.drop_index(op.f("ix_venta_items_producto_id"), table_name="venta_items")
    op.drop_index("ix_venta_items_movimiento_id", table_name="venta_items")
    op.drop_table("venta_items")
    op.drop_index("ix_ventas_created_at", table_name="ventas")
    op.drop_table("ventas")
    # ### end Alembic commands ###
