"""crea proveedores

Revision ID: 37840112ca70
Revises: 63276eeea69c
Create Date: 2026-09-08 13:48:11.113333

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37840112ca70"
down_revision: Union[str, Sequence[str], None] = "63276eeea69c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "proveedores",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("codigo", sa.String(length=20), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column("direccion", sa.String(length=200), nullable=True),
        sa.Column(
            "estado", sa.String(length=10), server_default="activo", nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "email IS NULL OR length(email) <= 254 /* email ~ '^[a-z0-9._%+-]+@[a-z0-9.-]+\\.[a-z]{2,}$' */",
            name="ck_proveedores_email",
        ),
        sa.CheckConstraint(
            "estado IN ('activo','inactivo')", name="ck_proveedores_estado"
        ),
        sa.CheckConstraint(
            "length(codigo) BETWEEN 3 AND 20 /* codigo ~ '^[A-Z0-9_-]{3,20}$' */",
            name="ck_proveedores_codigo_regex",
        ),
        sa.CheckConstraint(
            "direccion IS NULL OR length(trim(direccion)) BETWEEN 5 AND 200",
            name="ck_proveedores_direccion",
        ),
        sa.CheckConstraint(
            "length(trim(nombre)) BETWEEN 2 AND 100",
            name="ck_proveedores_nombre_length",
        ),
        sa.CheckConstraint(
            "telefono IS NULL OR length(telefono) BETWEEN 7 AND 20 /* telefono digitos 7-15 */",
            name="ck_proveedores_telefono",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_proveedores_codigo"), "proveedores", ["codigo"], unique=True
    )
    op.create_index(
        op.f("ix_proveedores_estado"), "proveedores", ["estado"], unique=False
    )
    op.create_index(
        op.f("ix_proveedores_nombre"), "proveedores", ["nombre"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_proveedores_nombre"), table_name="proveedores")
    op.drop_index(op.f("ix_proveedores_estado"), table_name="proveedores")
    op.drop_index(op.f("ix_proveedores_codigo"), table_name="proveedores")
    op.drop_table("proveedores")
    # ### end Alembic commands ###
