"""crea movimientos inventario

Revision ID: 63276eeea69c
Revises: 1a81a5e6e75b
Create Date: 2026-09-07 17:38:35.649388

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63276eeea69c"
down_revision: Union[str, Sequence[str], None] = "1a81a5e6e75b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "movimientos_inventario",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("producto_id", sa.Integer(), nullable=False),
        sa.Column("tipo", sa.String(length=10), nullable=False),
        sa.Column("cantidad", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("tipo IN ('entrada_inicial')", name="ck_movimientos_tipo"),
        sa.CheckConstraint(
            "cantidad > 0 AND cantidad <= 1000000", name="ck_movimientos_cantidad"
        ),
        sa.ForeignKeyConstraint(["producto_id"], ["productos.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_movimientos_producto_id",
        "movimientos_inventario",
        ["producto_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_movimientos_producto_id", table_name="movimientos_inventario")
    op.drop_table("movimientos_inventario")
    # ### end Alembic commands ###
