"""agrega stock_minimo a productos

Revision ID: 7010b4ddca09
Revises: 9111dba96a53
Create Date: 2026-09-09 17:32:01.969054

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7010b4ddca09"
down_revision: Union[str, Sequence[str], None] = "9111dba96a53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nota: tipo VARCHAR(10)->15 no se altera en SQLite (no valida longitud), solo se añade stock_minimo
    op.add_column(
        "productos",
        sa.Column("stock_minimo", sa.Integer(), server_default="0", nullable=False),
    )
    # Crear check para stock_minimo (SQLite lo soporta via batch)
    with op.batch_alter_table("productos", recreate="always") as batch_op:
        batch_op.create_check_constraint(
            "ck_productos_stock_minimo", "stock_minimo >= 0 AND stock_minimo <= 1000000"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("productos", recreate="always") as batch_op:
        batch_op.drop_constraint("ck_productos_stock_minimo", type_="check")
    op.drop_column("productos", "stock_minimo")
    # ### end Alembic commands ###
