"""extiende movimientos inventario 003

Revision ID: 9111dba96a53
Revises: 37840112ca70
Create Date: 2026-09-09 09:04:37.718029

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9111dba96a53"
down_revision: Union[str, Sequence[str], None] = "37840112ca70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite: add_column works without batch; checks/indexes via batch
    op.add_column(
        "movimientos_inventario", sa.Column("proveedor_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "movimientos_inventario",
        sa.Column("motivo", sa.String(length=200), nullable=True),
    )
    with op.batch_alter_table("movimientos_inventario", recreate="always") as batch_op:
        # Actualizar check de tipo para incluir entrada/salida
        try:
            batch_op.drop_constraint("ck_movimientos_tipo", type_="check")
        except Exception:
            pass
        batch_op.create_check_constraint(
            "ck_movimientos_tipo", "tipo IN ('entrada','salida','entrada_inicial')"
        )
        batch_op.create_check_constraint(
            "ck_movimientos_motivo",
            "motivo IS NULL OR length(trim(motivo)) BETWEEN 2 AND 200",
        )
        batch_op.create_check_constraint(
            "ck_movimientos_proveedor_entrada",
            "(tipo = 'entrada' AND proveedor_id IS NOT NULL) OR (tipo != 'entrada')",
        )
        batch_op.create_index("ix_movimientos_created_at", ["created_at"])
        batch_op.create_index("ix_movimientos_proveedor_id", ["proveedor_id"])
        batch_op.create_index("ix_movimientos_tipo", ["tipo"])
        batch_op.create_foreign_key(
            "fk_movimientos_proveedor_id",
            "proveedores",
            ["proveedor_id"],
            ["id"],
            ondelete="RESTRICT",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("movimientos_inventario", recreate="always") as batch_op:
        batch_op.drop_constraint("fk_movimientos_proveedor_id", type_="foreignkey")
        batch_op.drop_index("ix_movimientos_tipo")
        batch_op.drop_index("ix_movimientos_proveedor_id")
        batch_op.drop_index("ix_movimientos_created_at")
        batch_op.drop_constraint("ck_movimientos_tipo", type_="check")
        batch_op.create_check_constraint(
            "ck_movimientos_tipo", "tipo IN ('entrada_inicial')"
        )
        batch_op.drop_constraint("ck_movimientos_motivo", type_="check")
        batch_op.drop_constraint("ck_movimientos_proveedor_entrada", type_="check")
    op.drop_column("movimientos_inventario", "motivo")
    op.drop_column("movimientos_inventario", "proveedor_id")
    # ### end Alembic commands ###
